{
    'name': 'Security Services Management',
    'version': '17.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Manage guards, sites, shifts, payroll and complaints',
    'description': 'Complete security company management system.',
    'author': 'Jeremiah Kariuki',
    'depends': [
        'base',
        'hr',
        'account',
        'mail',
        'portal',
        'resource',
        'contacts',
        'bus',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/incident_sequence.xml',
        'data/complaint_sequence.xml',
        'wizard/hire_wizard_view.xml',
        'wizard/fire_wizard_view.xml',
        'views/guard_views.xml',
        'views/client_views.xml',
        'views/site_views.xml',
        'views/recruitment_views.xml',
        'views/shift_views.xml',
        'views/attendance_views.xml',
        'views/incident_views.xml',
        'views/complaint_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
